global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'socialink'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8081']
        labels:
          service: 'api-gateway'
          language: 'go'

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8083']
        labels:
          service: 'user-service'
          language: 'go'

  # Post Service
  - job_name: 'post-service'
    static_configs:
      - targets: ['post-service:8084']
        labels:
          service: 'post-service'
          language: 'go'

  # Messaging Service
  - job_name: 'messaging-service'
    static_configs:
      - targets: ['messaging-service:8091']
        labels:
          service: 'messaging-service'
          language: 'rust'

  # Settings Service
  - job_name: 'settings-service'
    static_configs:
      - targets: ['settings-service:8101']
        labels:
          service: 'settings-service'
          language: 'go'

  # Media Service
  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:8087']
        labels:
          service: 'media-service'
          language: 'rust'

  # Story Service
  - job_name: 'story-service'
    static_configs:
      - targets: ['story-service:8090']
        labels:
          service: 'story-service'
          language: 'scala'

  # Search Service
  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8089']
        labels:
          service: 'search-service'
          language: 'go'

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8088']
        labels:
          service: 'notification-service'
          language: 'scala'

  # Feed Service
  - job_name: 'feed-service'
    static_configs:
      - targets: ['feed-service:8085']
        labels:
          service: 'feed-service'
          language: 'python'

  # Community Service
  - job_name: 'community-service'
    static_configs:
      - targets: ['community-service:8093']
        labels:
          service: 'community-service'
          language: 'go'

  # Recommendation Service
  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:8095']
        labels:
          service: 'recommendation-service'
          language: 'python'

  # Streaming Service
  - job_name: 'streaming-service'
    static_configs:
      - targets: ['streaming-service:8097']
        labels:
          service: 'streaming-service'
          language: 'go'

  # Creator Service
  - job_name: 'creator-service'
    static_configs:
      - targets: ['creator-service:8100']
        labels:
          service: 'creator-service'
          language: 'go'

  # Databases
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
        labels:
          service: 'mongodb'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
        labels:
          service: 'elasticsearch'

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
        labels:
          service: 'kafka'
